version: '3'

services:
  scrapping:
    build: ./flats_scrapping
    image: scrap-image:latest
    command: ["scrapy", "crawl", "sreality"]
    volumes:
      - ./flats_scrapping:/app
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  server:
    image: server-image:latest
    build: ./flats_web
    ports:
      - "8080:8080"
    command: ["python3", "server.py"]
    depends_on:
      - database


